first_number = 10
second_number = 3
print(first_number ** second_number)
print(first_number * second_number)
print(first_number + second_number)
print(first_number - second_number)
print(first_number / second_number)
print(first_number // second_number)
print(first_number % second_number)
